# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('total_storey', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('postcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flatlet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('building_id', models.IntegerField()),
                ('room_id', models.CharField(max_length=60)),
                ('cost_type_id', models.IntegerField()),
                ('is_idle', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceMeters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flatlet_id', models.IntegerField()),
                ('res_name', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('meters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
