# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.IntegerField()),
                ('cost_num', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start', models.TimeField(auto_now_add=True)),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=15)),
                ('head_pic', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('is_left', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
